name: Mirror Dev Repository

on:
  push:
    branches:
      - dev


jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push Mirror
        run: |
          git config --global user.name "ip192htwhsnu[bot]"
          git config --global user.email "11410541@gs.hs.ntnu.edu.tw"
          git remote add mirror https://x-access-token:${{ secrets.HSCSHOP_MIRROR_DEPLOY }}@github.com/ip192htwhsnu/hscshop-dev-deploy.git
          git push mirror HEAD:main --force